### ISSUE TITLE
error missing table

### ISSUE THREAD

**Issue by abdkhakim** [imladrisol/onlineExam#2]
after install and i try php artisan migrate... and im get it.
how i resolved it. sorry im newbie ..
 [Illuminate\Database\QueryException]
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'new.roles' doesn
 't exist (SQL: select \* from `roles`)

 [PDOException]
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'new.roles' doesn
 't exist

**Comment by imladrisol** [comment]
Hello.
You should check if you have database 'new' and table 'roles' into it.
Did you execute 'php artisan migrate'?

**Comment by abdkhakim** [comment]
Yes, im do it..
But it's same...

**Comment by imladrisol** [comment]
Do you have another tables in your database 'new' except 'roles'?

**Comment by abdkhakim** [comment]
i think no...
im just trying this "copy project , install composer, and php artisan migrate". and this db is connected.

sorry im just newbie here...

**Comment by imladrisol** [comment]
You should create database with some name, for example 'new' by MySQL. Then, you have to edit .env file , set data for DB_.. section. Then, php artisan migrate.
