### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by khanriyaz617** [imladrisol/onlineExam#5]
I am getting this error.

Warning: require(D:\xampp\htdocs\oe\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\oe\bootstrap\autoload.php on line 18

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\oe\bootstrap/../vendor/autoload.php' (include_path='.;D:\xampp\php\PEAR') in D:\xampp\htdocs\oe\bootstrap\autoload.php on line 18

**Comment by imladrisol** [comment]
Try this one
http://stackoverflow.com/questions/28468625/laravel-5-failed-opening-required-bootstrap-vendor-autoload-php

**Comment by khanriyaz617** [comment]
I did composer update, its not working.

**Comment by imladrisol** [comment]
Try to change in file onlineExam/bootstrap/autoload.php in 17 line:
`require __DIR__.'../../vendor/autoload.php';`

**Comment by PSNAppz** [comment]
Try `composer install`
